// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ddeddccf-0765-41d2-adb8-5aa2d645fcc8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRelayStateChange();

String season;
float outsideTempF;
CloudSwitch relayState;
CloudTemperatureSensor insideTempF;
bool motionDetected;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(season, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outsideTempF, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relayState, READWRITE, ON_CHANGE, onRelayStateChange);
  ArduinoCloud.addProperty(insideTempF, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(motionDetected, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
